# Generated by Django 3.2 on 2021-08-10 16:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_app', '0022_alter_events_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 10, 21, 57, 13, 339165), help_text='Please use the following format: <em>YYYY-MM-DD</em>.'),
        ),
        migrations.AlterField(
            model_name='events',
            name='eventType',
            field=models.CharField(choices=[('Panel Session', 'Panel Session'), ('Workshop', 'Workshop'), ('Hackathon', 'Hackathon'), ('FunLearning', 'FunLearning'), ('Competition', 'Competition'), ('ESummit21', 'ESummit21')], default='Panel Session', max_length=13),
        ),
    ]
