# Generated by Django 3.2 on 2021-08-27 17:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_app', '0023_auto_20210810_2157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plandemic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOfTeam', models.CharField(max_length=50)),
                ('leaderEmail', models.EmailField(max_length=254)),
                ('leaderName', models.CharField(max_length=100)),
                ('leaderContact', models.CharField(max_length=50)),
                ('college', models.CharField(default='K. J. Somaiya College of Engineering', max_length=255)),
                ('alternateEmail', models.EmailField(max_length=254)),
                ('alternateContact', models.CharField(max_length=50)),
                ('nameOfMembers', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='events',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 27, 23, 22, 53, 793270), help_text='Please use the following format: <em>YYYY-MM-DD</em>.'),
        ),
    ]
