# Generated by Django 3.2 on 2021-08-27 18:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_app', '0024_auto_20210827_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plandemic',
            name='alternateContact',
        ),
        migrations.RemoveField(
            model_name='plandemic',
            name='alternateEmail',
        ),
        migrations.AlterField(
            model_name='events',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 27, 23, 39, 27, 489724), help_text='Please use the following format: <em>YYYY-MM-DD</em>.'),
        ),
    ]
