# Generated by Django 3.2.5 on 2022-09-13 16:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_app', '0025_auto_20210827_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 13, 21, 54, 1, 565505), help_text='Please use the following format: <em>YYYY-MM-DD</em>.'),
        ),
        migrations.AlterField(
            model_name='events',
            name='eventType',
            field=models.CharField(choices=[('Speaker Session', 'Speaker Session'), ('Panel Session', 'Panel Session'), ('Workshop', 'Workshop'), ('Hackathon', 'Hackathon'), ('FunLearning', 'FunLearning'), ('Competition', 'Competition'), ('ESummit21', 'ESummit21')], default='Panel Session', max_length=20),
        ),
    ]
