# Generated by Django 3.2 on 2022-10-21 14:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_app', '0026_auto_20220913_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 21, 20, 7, 51, 92268), help_text='Please use the following format: <em>YYYY-MM-DD</em>.'),
        ),
        migrations.AlterField(
            model_name='events',
            name='eventType',
            field=models.CharField(choices=[('Speaker Session', 'Speaker Session'), ('Panel Session', 'Panel Session'), ('Workshop', 'Workshop'), ('Hackathon', 'Hackathon'), ('FunLearning', 'FunLearning'), ('Competition', 'Competition'), ('ESummit21', 'ESummit21'), ('ESummit22', 'ESummit22')], default='Panel Session', max_length=20),
        ),
    ]
