# Generated by Django 3.2.5 on 2023-02-26 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_app', '0031_alter_events_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 26, 15, 18, 22, 398117), help_text='Please use the following format: <em>YYYY-MM-DD</em>.'),
        ),
    ]
